services:
  retoolbox:
    build:
      context: .
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.retoolbox.rule=Host(`yonliud.dev`) && PathPrefix(`/toolbox`)"
      - "traefik.http.routers.retoolbox.entrypoints=web"
      - "traefik.http.services.retoolbox.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
